export const ActionTypes = {
    GET_TEACHER_DETAIL: "GET_TEACHER_DETAIL",
    REGISTER_DATA: "REGISTER_DATA",
    SET_TEACHER_REGISTRAION: "SET_TEACHER_REGISTRATION",
    IS_EMAIL_ID_VALID: "IS_EMAIL_ID_VALID"
}