export const ActionTypes = {
  GET_TEACHER_DETAIL: "GET_TEACHER_DETAIL",
  REGISTER_DATA: "REGISTER_DATA",
  SET_TEACHER_REGISTRAION: "SET_TEACHER_REGISTRATION",
  IS_EMAIL_ID_VALID: "IS_EMAIL_ID_VALID",
  SET_EMAIL_STATE: "SET_EMAIL_STATE",
  SET_STUDENT_DETAIL: "SET_STUDENT_DETAIL",
  SET_FILTER_DATA: "SET_FILTER_DATA",
  SET_FILTER_OBJECT: "SET_FILTER_OBJECT",
  GET_IMPACT: "GET_IMPACT",
};
